/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_illcode_sdljoystick4java_Native */

#ifndef _Included_com_illcode_sdljoystick4java_Native
#define _Included_com_illcode_sdljoystick4java_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_illcode_sdljoystick4java_Native
 * Method:    getDirectByteBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_illcode_sdljoystick4java_Native_getDirectByteBufferAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
